### ISSUE TITLE
perhaps use standard OSM maps as a base?

### ISSUE THREAD

**Issue by waldenn** [Abbe98/map-search#2]
Hi,

I had to chang the base layer to the standard OSM map in "src/components/Leaflet.vue", because I got the [429 HTTP error code](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429).

```js
    L.tileLayer( 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      attribution: 'Background &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(map);
```
Great project  idea. Thanks!

**Comment by Abbe98** [comment]
Yes third party tools on non Wikimedia servers can only access tiles in the Wikimedia cache. I will keep the Wikimedia tiles there for consistency among Wikimedia tools and for privacy/policy reasons.
